#  ############################################################################# #
#  Author       : dmike
#  Date         : 2,October 2016
#  Description  : Principal Make file
#
#  Default KBUILD file that does not define only the language variable.
#  Setting it to 'cc'.
#
#  ############################################################################# #
languages := packages
install_language := packages
mode := color_
debug := @

src_root := packs
dep_root := $(empty)

# ############################################################################## #
# Plugin variables definition
# ############################################################################## #
# KERNELDIR := /lib/modules/$(shell uname -r)/build
# mod_name :=
# ASMFLAGS := -f elf64 -g dwarf2

# export KERNELDIR mod_name ASMFLAGS

#  ############################################################################# #
#  Command definition.
#  ############################################################################# #
CC := gcc
LD := ld
RM := rm
MV := mv
CP := cp
INSTALL := install
MKDIR:= mkdir
AR:= ar
RANLIB:= ranlib
DOCKER:= docker
GIT:= git
GO:= go
INSMOD := insmod
RMMOD := rmmod
ASM := yasm
CTEX := pdflatex
FTEX := .pdf

export CC LD RM MKDIR AR RANLIB DOCKER GIT GO INSMOD RMMOD ASM CP INSTALL CTEX FTEX
