#  ############################################################################# #
#  Author       : dmike
#  Date         : 2,October 2016
#  Description  : Principal Make file
#
#  Default KBUILD file that does not define only the language variable.
#  Setting it to 'cc'.
#
#  ############################################################################# #
languages := golang
install_language := golang
mode := color_
debug := @

src_root := mod
dep_root := $(empty)
project_name := hello

# ############################################################################## #
# Plugin variables definition
# ############################################################################## #
# KERNELDIR := /lib/modules/$(shell uname -r)/build
mod_name := github.com/dual-lab/the-chamber-of-go/packs/hello
# ASMFLAGS := -f elf64 -g dwarf2

# export KERNELDIR mod_name ASMFLAGS
export mod_name

# ) ############################################################################# #
#  Command definition.
#  ############################################################################# #
CC := gcc
LD := ld
RM := rm
MV := mv
CP := cp
INSTALL := install
MKDIR:= mkdir
AR:= ar
RANLIB:= ranlib
DOCKER:= docker
GIT:= git
GO:= go
INSMOD := insmod
RMMOD := rmmod
ASM := yasm
CTEX := pdflatex
FTEX := .pdf

export CC LD RM MKDIR AR RANLIB DOCKER GIT GO INSMOD RMMOD ASM CP INSTALL CTEX FTEX
